spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoticket_test
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
  cache:
    type: simple

security:
  jwt:
    secret_key: ${JWT_SECRET}
    token_expiration: 86400000
    refresh_window: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    distribution:
      percentiles-histogram:
        http.server:
          requests: true

