spring:
  application:
    name: autoticketapp
  profiles:
    active: ${PROFILE}

app:
  kafka:
    bootstrap-servers: localhost:9092
    group-id: spring-service-group
    topics:
      ticket:
        classification:
          request: ticket.classification.request
          response: ticket.classification.response
    schema-registry-url: http://localhost:8081
