package com.curso.autoticketapp.ticket.infrastructure.event.consumer.specific;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketProcessingEvent;
import com.curso.autoticketapp.common.infrastructure.event.consumer.EventSpecificConsumer;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class TicketProcessingConsumer implements EventSpecificConsumer<TicketProcessingEvent> {

    @Override
    public void accept(Message<TicketProcessingEvent> genericRecordMessage) {

    }

    @Override
    public String getSchema() {
        return TicketProcessingEvent.getClassSchema().getFullName();
    }
}
