package com.curso.autoticketapp.ticket.infrastructure.event.consumer.specific;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketCompletedEvent;
import com.curso.autoticketapp.common.application.mediator.Mediator;
import com.curso.autoticketapp.common.infrastructure.event.consumer.EventSpecificConsumer;
import com.curso.autoticketapp.ticket.application.command.create.ticketdetails.CreateTicketAnalysisRequest;
import com.curso.autoticketapp.ticket.domain.entity.Ticket;
import com.curso.autoticketapp.ticket.domain.exceptions.TicketNotFoundException;
import com.curso.autoticketapp.ticket.domain.port.TicketRepository;
import com.curso.autoticketapp.ticket.infrastructure.event.mapper.TicketEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

import java.util.UUID;

@Slf4j
@Component
@RequiredArgsConstructor
public class TicketCompletedConsumer implements EventSpecificConsumer<TicketCompletedEvent> {

    private final Mediator mediator;

    private final TicketEventMapper ticketEventMapper;

    private final TicketRepository ticketRepository;

    @Override
    public void accept(Message<TicketCompletedEvent> genericRecordMessage) {
        UUID ticketUUID = genericRecordMessage.getPayload().getUuid();

        Long ticketId = ticketRepository.findByUUID(ticketUUID)
                .orElseThrow(() -> new TicketNotFoundException(ticketUUID))
                .getId();

        CreateTicketAnalysisRequest request = ticketEventMapper.mapToCreateTicketAnalysisRequest(genericRecordMessage.getPayload());
        request.setTicketId(ticketId);

        mediator.dispatch(request);
    }

    @Override
    public String getSchema() {
        return TicketCompletedEvent.getClassSchema().getFullName();
    }
}
