package com.curso.autoticketapp.ticket.infrastructure.event.consumer.specific;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketFailedEvent;
import com.curso.autoticketapp.common.infrastructure.event.consumer.EventSpecificConsumer;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class TicketFailedConsumer implements EventSpecificConsumer<TicketFailedEvent> {

    @Override
    public void accept(Message<TicketFailedEvent> genericRecordMessage) {

    }

    @Override
    public String getSchema() {
        return TicketFailedEvent.getClassSchema().getFullName();
    }
}
