package com.curso.autoticketapp.ticket.infrastructure.event.temp;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketCompletedEvent;
import com.curso.autoticketapp.autogenerated.events.ticket.TicketRequestedEvent;
import com.curso.autoticketapp.common.infrastructure.event.producer.KafkaProducer;
import com.curso.autoticketapp.ticket.domain.entity.enums.TicketCategory;
import com.curso.autoticketapp.ticket.domain.entity.enums.TicketSentiment;
import com.curso.autoticketapp.ticket.domain.entity.enums.TicketUrgency;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

import java.util.function.Consumer;

@Slf4j
@Component
@RequiredArgsConstructor
public class TicketRequestedConsumer implements Consumer<TicketRequestedEvent> {

    private final KafkaProducer kafkaProducer;

    @Value("${app.kafka.topics.ticket.classification.response}")
    private String responseTopic;

    @Override
    @KafkaListener(
            topics = "${app.kafka.topics.ticket.classification.request}",
            groupId = "${app.kafka.group-id}",
            containerFactory = "kafkaListenerContainerFactory"
    )
    public void accept(TicketRequestedEvent ticketRequestedEvent) {
        log.info("Requested event recived: {}", ticketRequestedEvent);
        try {
            CharSequence category = TicketCategory.GENERAL.name();
            CharSequence sentiment = TicketSentiment.POSITIVE.name();
            CharSequence urgency = TicketUrgency.LOW.name();

            TicketCompletedEvent event = TicketCompletedEvent.newBuilder()
                    .setUuid(ticketRequestedEvent.getUuid())
                    .setCategory(category)
                    .setSentiment(sentiment)
                    .setUrgency(urgency)
                    .setTimestamp(System.currentTimeMillis())
                    .build();

            kafkaProducer.send(responseTopic, event);
        } catch (Exception e) {
            log.error("Exception: {}", e.toString());
        }
    }
}
