package com.curso.autoticketapp.ticket.infrastructure.event.consumer;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketCompletedEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.BackOff;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.annotation.RetryableTopic;
import org.springframework.stereotype.Component;

import java.util.function.Consumer;

@Slf4j
@Component
@RequiredArgsConstructor
public class TicketCompletedConsumer implements Consumer<TicketCompletedEvent> {

    @Override
    @KafkaListener(
            topics = "${app.kafka.topics.ticket.classification.completed}",
            groupId = "${app.kafka.group-id}",
            containerFactory = "kafkaListenerContainerFactory"
    )
    public void accept(TicketCompletedEvent ticketCompletedEvent) {

        log.info("Completed event recived: {}", ticketCompletedEvent);
    }

}
