package com.curso.autoticketapp.ticket.infrastructure.api;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketRequestedEvent;
import com.curso.autoticketapp.common.application.mediator.Mediator;
import com.curso.autoticketapp.common.domain.enums.UserRole;
import com.curso.autoticketapp.common.domain.pagination.PaginationQuery;
import com.curso.autoticketapp.common.domain.pagination.PaginationResult;
import com.curso.autoticketapp.common.infrastructure.event.producer.KafkaProducer;
import com.curso.autoticketapp.common.infrastructure.services.JwtService;
import com.curso.autoticketapp.ticket.application.command.create.ticket.CreateTicketRequest;
import com.curso.autoticketapp.ticket.application.command.create.ticket.CreateTicketResponse;
import com.curso.autoticketapp.ticket.application.query.getall.GetAllTicketsRequest;
import com.curso.autoticketapp.ticket.application.query.getall.GetAllTicketsResponse;
import com.curso.autoticketapp.ticket.application.query.getbyid.GetTicketByPublicIdRequest;
import com.curso.autoticketapp.ticket.application.query.getbyid.GetTicketByPublicIdResponse;
import com.curso.autoticketapp.ticket.domain.entity.TicketFilter;
import com.curso.autoticketapp.ticket.domain.entity.enums.TicketPriority;
import com.curso.autoticketapp.ticket.domain.entity.enums.TicketStatus;
import com.curso.autoticketapp.ticket.infrastructure.api.dto.CreateTicketDTO;
import com.curso.autoticketapp.ticket.infrastructure.api.dto.CreateTicketResponseDTO;
import com.curso.autoticketapp.ticket.infrastructure.api.dto.TicketDTO;
import com.curso.autoticketapp.ticket.infrastructure.api.mapper.TicketMapper;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping(TicketController.BASE_URL)
@Tag(name = "Ticket", description = "Ticket API operations")
@SecurityRequirement(name = "Bearer Authentication")
@RequiredArgsConstructor
public class TicketController implements TicketAPI {

    public static final String BASE_URL = "/api/v1/tickets";

    @Value("${app.kafka.topics.ticket.classification.request}")
    private String ticketRequestTopic;

    private final Mediator mediator;

    private final TicketMapper ticketMapper;

    private final JwtService jwtService;

    private final KafkaProducer kafkaProducer;

    @PostMapping
    @Override
    @PreAuthorize("hasAnyAuthority('CLIENT', 'AGENT')")
    public ResponseEntity<CreateTicketResponseDTO> createTicket(
            @ModelAttribute CreateTicketDTO createTicketDTO,
            @RequestHeader(name = "Authorization") String token
    ) {
        Long user_id = jwtService.getUserId(token.substring(7));

        CreateTicketRequest request = ticketMapper.mapToCreateTicketRequest(createTicketDTO);
        request.setUserId(user_id);

        CreateTicketResponse response = mediator.dispatch(request);

        TicketRequestedEvent event = TicketRequestedEvent.newBuilder()
                .setUuid(response.uuid())
                .setSubject(request.getSubject())
                .setDescription(request.getDescription())
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send(ticketRequestTopic, event);

        return ResponseEntity.ok(ticketMapper.mapToCreateTicketResponseDTO(response));
    }

    @GetMapping
    @Override
    @PreAuthorize("hasAnyAuthority('CLIENT', 'AGENT')")
    public ResponseEntity<PaginationResult<TicketDTO>> getAllTickets(
            @RequestParam(defaultValue = "0") int pageNumber,
            @RequestParam(defaultValue = "5") int pageSize,
            @RequestParam(defaultValue = "id") String sortBy,
            @RequestParam(defaultValue = "asc") String direction,
            @RequestParam(required = false) String subject,
            @RequestParam(required = false) String description,
            @RequestParam(required = false) TicketStatus status,
            @RequestParam(required = false) TicketPriority priority,
            @RequestHeader(name = "Authorization") String token,
            Authentication authentication
    ) {
        PaginationQuery pageQuery = PaginationQuery.builder()
                .page(pageNumber)
                .size(pageSize)
                .sortBy(sortBy)
                .direction(direction)
                .build();

        TicketFilter filter = TicketFilter.builder()
                .subject(subject)
                .description(description)
                .status(status)
                .priority(priority)
                .build();

        List<UserRole> roles = authentication.getAuthorities()
                .stream()
                .map(e -> UserRole.valueOf(e.getAuthority()))
                .toList();

        Long userId = jwtService.getUserId(token.substring(7));

        GetAllTicketsRequest request = new GetAllTicketsRequest(pageQuery, filter, userId, roles);

        GetAllTicketsResponse response = mediator.dispatch(request);

        return ResponseEntity.ok(ticketMapper.mapToPaginationTicketDTO(response.ticketsPage()));
    }

    @Override
    @GetMapping("{public_id}")
    @PreAuthorize("hasAnyAuthority('CLIENT', 'AGENT')")
    public ResponseEntity<TicketDTO> getTicketByPublicId(
            @PathVariable String public_id,
            @RequestHeader(name = "Authorization") String token,
            Authentication authentication
    ) {
        List<UserRole> roles = authentication.getAuthorities()
                .stream()
                .map(e -> UserRole.valueOf(e.getAuthority()))
                .toList();

        Long userId = jwtService.getUserId(token.substring(7));

        GetTicketByPublicIdRequest request = new GetTicketByPublicIdRequest(public_id, userId, roles);

        GetTicketByPublicIdResponse response = mediator.dispatch(request);

        return ResponseEntity.ok(ticketMapper.mapToTicketDTO(response.ticket()));
    }

}
