package com.curso.autoticketapp.ticket.domain.port;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketRequestedEvent;

public interface TicketEvent {

    void sendTicketRequested(TicketRequestedEvent event);

}
