package com.curso.autoticketapp.ticket.infrastructure.event.mapper;

import com.curso.autoticketapp.autogenerated.events.ticket.TicketCompletedEvent;
import com.curso.autoticketapp.common.infrastructure.event.utils.MapperUtils;
import com.curso.autoticketapp.ticket.application.command.create.ticketdetails.CreateTicketAnalysisRequest;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, unmappedTargetPolicy = ReportingPolicy.ERROR)

public interface TicketEventMapper extends MapperUtils {

    @Mapping(target = "ticketId", ignore = true)
    CreateTicketAnalysisRequest mapToCreateTicketAnalysisRequest(TicketCompletedEvent event);

}
